export {default as DashBoard} from "./IntailScreens/DashBoard"
export {default as Login} from "./Login/Login"
export {default as SignUp} from "./SignUp/SignUp"
export {default as Chat} from "./Chat/Chat"
export {default as Map} from "./Map/Map"
export {default as Stories} from "./Stories/Stories"
export {default as Friends} from "./Friends/Friends"
export {default as Camera} from "./Camera/Camera"